---
- name: Install default packages
  apt: pkg={{ item }} state=installed
  with_items: ${system_packages}

- name: Install Debian specific packages
  apt: pkg={{ item }} state=latest
  with_items: debian_system_packages
  when: ansible_lsb.id == 'Debian'

- name: Install Ubuntu specific packages
  apt: pkg={{ item }} state=latest
  with_items: ubuntu_system_packages
  when: ansible_lsb.id == 'Ubuntu'

# Repositories
- include: dotdeb.yml

# System stuff
- include: hostname.yml
- include: timezone.yml

# Users stuff
- include: users.yml
- include: ssh_keys.yml
- include: prezto.yml
- include: tmux.yml

# Services
- include: ntp.yml
