---
- name: Clone Prezto from Github
  tags: prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest={{ item.home }}/.zprezto update=no
  with_items: users

- name: Set the correct permissions on the Prezto working repository
  tags: prezto
  file: dest={{ item.home }}/.zprezto owner={{ item.name }} group={{ item.name }} state=directory
  with_items: users

- name: Link zlogin for Prezto
  tags: prezto
  file: src={{ item.home }}/.zprezto/runcoms/zlogin dest={{ item.home }}/.zlogin owner={{ item.name }} group={{ item.name }} state=link
  with_items: users

- name: Link zlogout for Prezto
  tags: prezto
  file: src={{ item.home }}/.zprezto/runcoms/zlogout dest={{ item.home }}/.zlogout owner={{ item.name }} group={{ item.name }} state=link
  with_items: users

- name: Create zpreztorc
  tags: prezto
  template: src=zsh/zpreztorc.j2 dest={{ item.home }}/.zpreztorc owner={{ item.name }} group={{ item.name }}
  with_items: users

- name: Install Sphax Prezto theme
  tags: prezto
  copy: src=zsh/sphax_theme dest={{ item.home }}/.zprezto/modules/prompt/functions/prompt_sphax_setup owner={{ item.name }} group={{ item.name }}
  with_items: users

- name: Link needed files for Prezto
  tags: prezto
  file: src={{ item[0].home }}/.zprezto/runcoms/{{ item[1] }} dest={{ item[0].home }}/.{{ item[1] }} owner={{ item[0].name }} group={{ item[0].name }} state=link
  with_nested:
    - users
    - { zprofile, zshenv, zshrc }
