---
- name: Create all users
  tags: users
  user: name={{ item.name }} createhome={{ item.createhome }} home={{ item.home }} shell={{ item.shell }} generate_ssh_key=yes ssh_key_bits=4096 state=present
  with_items: users
  when: users is defined

- name: Set the SSH configuration file
  tags: users
  copy: src=ssh_config dest=/root/.ssh/config owner=root group=root mode=0600
